/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Interfaces.Centers.center;
import java.awt.Color;
import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class Date_Time extends javax.swing.JFrame {

    /**
     * Creates new form KAHCenter
     */
    public static String date;
    public static String time;

    public Date_Time() {
        initComponents();

        ImageIcon Menu = new ImageIcon("Icon\\menu.png");
        ImageIcon MenuS = new ImageIcon(Menu.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        MenuIcon.setIcon(MenuS);

        ImageIcon cal = new ImageIcon("Icon\\calendar.png");
        ImageIcon calS = new ImageIcon(cal.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH));
        calIcon.setIcon(calS);

        ImageIcon Battery = new ImageIcon("Icon\\battery-status.png");
        ImageIcon BatteryS = new ImageIcon(Battery.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        BatteryIcon.setIcon(BatteryS);

        ImageIcon WiFi = new ImageIcon("Icon\\wifi.png");
        ImageIcon WiFiS = new ImageIcon(WiFi.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        WiFiIcon.setIcon(WiFiS);

        ImageIcon Network = new ImageIcon("Icon\\signal.png");
        ImageIcon NetworkS = new ImageIcon(Network.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        NetworkIcon.setIcon(NetworkS);
        CertainCenter.setText(center + " Center");

        //DayComboBox.getItems().addAll()
        //(new Int{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PinkBackground = new javax.swing.JPanel();
        UbMenu = new javax.swing.JPanel();
        Text = new javax.swing.JLabel();
        MenuIcon = new javax.swing.JLabel();
        NextLabel = new javax.swing.JLabel();
        calIcon = new javax.swing.JLabel();
        CertainCenter = new javax.swing.JLabel();
        HomepageText2 = new javax.swing.JLabel();
        BackLabel = new javax.swing.JLabel();
        HomepageText4 = new javax.swing.JLabel();
        PhoneInfoPanel = new javax.swing.JPanel();
        TimeIcon = new javax.swing.JLabel();
        BatteryIcon = new javax.swing.JLabel();
        WiFiIcon = new javax.swing.JLabel();
        NetworkIcon = new javax.swing.JLabel();
        DayComboBox = new javax.swing.JComboBox<>();
        MonthComboBox = new javax.swing.JComboBox<>();
        DateLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        MinuteComboBox1 = new javax.swing.JComboBox<>();
        HourComboBox2 = new javax.swing.JComboBox<>();
        Date_Error = new javax.swing.JLabel();
        Time_Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PinkBackground.setBackground(new java.awt.Color(255, 230, 230));
        PinkBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UbMenu.setBackground(new java.awt.Color(255, 204, 204));
        UbMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        Text.setText("Blood Donation");
        Text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        UbMenu.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 28));
        UbMenu.add(MenuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 30, 30));

        PinkBackground.add(UbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 50));

        NextLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        NextLabel.setText("Next >");
        NextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextLabelMouseClicked(evt);
            }
        });
        PinkBackground.add(NextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));
        PinkBackground.add(calIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 100));

        CertainCenter.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        CertainCenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PinkBackground.add(CertainCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 250, 60));

        HomepageText2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        HomepageText2.setForeground(new java.awt.Color(178, 169, 169));
        HomepageText2.setText("_________________________");
        PinkBackground.add(HomepageText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        BackLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        BackLabel.setText("< Back");
        BackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackLabelMousePressed(evt);
            }
        });
        PinkBackground.add(BackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        HomepageText4.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        HomepageText4.setForeground(new java.awt.Color(178, 169, 169));
        HomepageText4.setText("_________________________");
        PinkBackground.add(HomepageText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        PhoneInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        PhoneInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TimeIcon.setFont(new java.awt.Font("Book Antiqua", 1, 13)); // NOI18N
        TimeIcon.setText("12:00");

        BatteryIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        WiFiIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        NetworkIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        javax.swing.GroupLayout PhoneInfoPanelLayout = new javax.swing.GroupLayout(PhoneInfoPanel);
        PhoneInfoPanel.setLayout(PhoneInfoPanelLayout);
        PhoneInfoPanelLayout.setHorizontalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhoneInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeIcon)
                .addGap(202, 202, 202)
                .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        PhoneInfoPanelLayout.setVerticalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhoneInfoPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PinkBackground.add(PhoneInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 20));

        DayComboBox.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N
        DayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        DayComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DayComboBox.setFocusTraversalPolicyProvider(true);
        DayComboBox.setName(""); // NOI18N
        DayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayComboBoxActionPerformed(evt);
            }
        });
        PinkBackground.add(DayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 70, 28));

        MonthComboBox.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N
        MonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February ", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        PinkBackground.add(MonthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 80, 28));

        DateLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        DateLabel.setText("Date: ");
        PinkBackground.add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        TimeLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        TimeLabel.setText("Time: ");
        PinkBackground.add(TimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        MinuteComboBox1.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N
        MinuteComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minute", "00", "15", "30", "45" }));
        MinuteComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MinuteComboBox1.setFocusTraversalPolicyProvider(true);
        MinuteComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinuteComboBox1ActionPerformed(evt);
            }
        });
        PinkBackground.add(MinuteComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 308, 80, 28));

        HourComboBox2.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N
        HourComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hour", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        HourComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HourComboBox2.setFocusTraversalPolicyProvider(true);
        HourComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourComboBox2ActionPerformed(evt);
            }
        });
        PinkBackground.add(HourComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 308, 70, 28));

        Date_Error.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        Date_Error.setForeground(new java.awt.Color(255, 51, 51));
        PinkBackground.add(Date_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 120, 20));

        Time_Error.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        Time_Error.setForeground(new java.awt.Color(255, 51, 51));
        PinkBackground.add(Time_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PinkBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PinkBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMousePressed
        // TODO add your handling code here:
        dispose();
        Centers C = new Centers();
        C.setVisible(true);
    }//GEN-LAST:event_BackLabelMousePressed

    private void DayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DayComboBoxActionPerformed

    private void HourComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HourComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HourComboBox2ActionPerformed

    private void MinuteComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinuteComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinuteComboBox1ActionPerformed

    private void NextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextLabelMouseClicked

        if (checkInfo()) {
            dispose();
            Booking b = new Booking();
            b.setVisible(true);
        }
    }//GEN-LAST:event_NextLabelMouseClicked

    public boolean checkInfo() {
        boolean valid = true;
        Date_Error.setText("  ");
        Time_Error.setText("  ");
        Date d = new Date();

        // if the user didn't choose 
        if (DayComboBox.getSelectedIndex() == 0 || MonthComboBox.getSelectedIndex() == 0) {
            Date_Error.setText("choose a date");
            Date_Error.setForeground(Color.red);
            valid = false;
        } else {
            
            d.setDate((int) DayComboBox.getSelectedIndex());
            d.setMonth((int) MonthComboBox.getSelectedIndex()-1);
        }
        
        // if user choose a date on the past
        if (!checkDate(d)) {
            Date_Error.setText("choose a date on future");
            Date_Error.setForeground(Color.red);
            valid = false;
        } else {
            date =  d.getDate()+ ", "+MonthComboBox.getSelectedItem();
        }
        
        // if user didn't choose time
        if (HourComboBox2.getSelectedIndex() == 0 || MinuteComboBox1.getSelectedIndex() == 0) {
            Time_Error.setText("choose a time");
            Time_Error.setForeground(Color.red);
            valid = false;
        } else {
            time = HourComboBox2.getSelectedItem() + ":" + MinuteComboBox1.getSelectedItem();
        }

        return valid;
    }

// --------- check if selected date in past ---------
    public boolean checkDate(Date selectedDate) {
        boolean checker = true;

        Date today = new Date();
        int currentDay = today.getDate();
        int currentMonth = today.getMonth();

        int selectedDay = selectedDate.getDate();
        int selectedMonth = selectedDate.getMonth();

        if (currentDay == selectedDay && currentMonth == selectedMonth) {
            checker = true;
            
        } else if (selectedDate.before(today)) {
            checker = false;
        }

        return checker;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Date_Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Date_Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Date_Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Date_Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Date_Time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLabel;
    private javax.swing.JLabel BatteryIcon;
    private javax.swing.JLabel CertainCenter;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel Date_Error;
    private javax.swing.JComboBox<String> DayComboBox;
    private javax.swing.JLabel HomepageText2;
    private javax.swing.JLabel HomepageText4;
    private javax.swing.JComboBox<String> HourComboBox2;
    private javax.swing.JLabel MenuIcon;
    private javax.swing.JComboBox<String> MinuteComboBox1;
    private javax.swing.JComboBox<String> MonthComboBox;
    private javax.swing.JLabel NetworkIcon;
    private javax.swing.JLabel NextLabel;
    private javax.swing.JPanel PhoneInfoPanel;
    private javax.swing.JPanel PinkBackground;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel TimeIcon;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel Time_Error;
    private javax.swing.JPanel UbMenu;
    private javax.swing.JLabel WiFiIcon;
    private javax.swing.JLabel calIcon;
    // End of variables declaration//GEN-END:variables
}
