/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Interfaces.Centers.center;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author hp
 */
public class Date extends javax.swing.JFrame {

    /**
     * Creates new form KAHCenter
     */
    
    public static String date;
    
    public Date() {
        initComponents();
        
        ImageIcon Menu = new ImageIcon("Icon\\menu.png");
        ImageIcon MenuS = new ImageIcon(Menu.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        MenuIcon.setIcon(MenuS);        
        
        ImageIcon cal = new ImageIcon("Icon\\calendar.png");
        ImageIcon calS = new ImageIcon(cal.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH));
        calIcon.setIcon(calS);
        
        ImageIcon Battery = new ImageIcon("Icon\\battery-status.png");
        ImageIcon BatteryS = new ImageIcon(Battery.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        BatteryIcon.setIcon(BatteryS);
        
        ImageIcon WiFi = new ImageIcon("Icon\\wifi.png");
        ImageIcon WiFiS = new ImageIcon(WiFi.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        WiFiIcon.setIcon(WiFiS);
        
        ImageIcon Network = new ImageIcon("Icon\\signal.png");
        ImageIcon NetworkS = new ImageIcon(Network.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        NetworkIcon.setIcon(NetworkS);
        CertainCenter.setText(center + " Center");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PinkBackground = new javax.swing.JPanel();
        UbMenu = new javax.swing.JPanel();
        Text = new javax.swing.JLabel();
        MenuIcon = new javax.swing.JLabel();
        NextLabel = new javax.swing.JLabel();
        calIcon = new javax.swing.JLabel();
        CertainCenter = new javax.swing.JLabel();
        HomepageText2 = new javax.swing.JLabel();
        BackLabel = new javax.swing.JLabel();
        NJP = new javax.swing.JPanel();
        Jan19 = new javax.swing.JLabel();
        TJP = new javax.swing.JPanel();
        Jan20 = new javax.swing.JLabel();
        TFJP = new javax.swing.JPanel();
        Jan25 = new javax.swing.JLabel();
        TTJP = new javax.swing.JPanel();
        Jan30 = new javax.swing.JLabel();
        HomepageText4 = new javax.swing.JLabel();
        PhoneInfoPanel = new javax.swing.JPanel();
        TimeIcon = new javax.swing.JLabel();
        BatteryIcon = new javax.swing.JLabel();
        WiFiIcon = new javax.swing.JLabel();
        NetworkIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PinkBackground.setBackground(new java.awt.Color(255, 230, 230));
        PinkBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UbMenu.setBackground(new java.awt.Color(255, 204, 204));
        UbMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        Text.setText("Blood Donation");
        Text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        UbMenu.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 28));
        UbMenu.add(MenuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 30, 30));

        PinkBackground.add(UbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 50));

        NextLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        NextLabel.setText("Next >");
        PinkBackground.add(NextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));
        PinkBackground.add(calIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 100));

        CertainCenter.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        CertainCenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PinkBackground.add(CertainCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 250, 60));

        HomepageText2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        HomepageText2.setForeground(new java.awt.Color(178, 169, 169));
        HomepageText2.setText("_________________________");
        PinkBackground.add(HomepageText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        BackLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        BackLabel.setText("< Back");
        BackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackLabelMousePressed(evt);
            }
        });
        PinkBackground.add(BackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        NJP.setBackground(new java.awt.Color(255, 255, 255));

        Jan19.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        Jan19.setText("  19 Jan");
        Jan19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Jan19MousePressed(evt);
            }
        });

        javax.swing.GroupLayout NJPLayout = new javax.swing.GroupLayout(NJP);
        NJP.setLayout(NJPLayout);
        NJPLayout.setHorizontalGroup(
            NJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jan19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        NJPLayout.setVerticalGroup(
            NJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jan19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PinkBackground.add(NJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, 50));

        TJP.setBackground(new java.awt.Color(255, 255, 255));

        Jan20.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        Jan20.setText("  20 Jan");
        Jan20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Jan20MousePressed(evt);
            }
        });

        javax.swing.GroupLayout TJPLayout = new javax.swing.GroupLayout(TJP);
        TJP.setLayout(TJPLayout);
        TJPLayout.setHorizontalGroup(
            TJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jan20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        TJPLayout.setVerticalGroup(
            TJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jan20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PinkBackground.add(TJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        TFJP.setBackground(new java.awt.Color(255, 255, 255));

        Jan25.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        Jan25.setText("  25 Jan");
        Jan25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Jan25MousePressed(evt);
            }
        });

        javax.swing.GroupLayout TFJPLayout = new javax.swing.GroupLayout(TFJP);
        TFJP.setLayout(TFJPLayout);
        TFJPLayout.setHorizontalGroup(
            TFJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(TFJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Jan25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        TFJPLayout.setVerticalGroup(
            TFJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(TFJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Jan25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        PinkBackground.add(TFJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        TTJP.setBackground(new java.awt.Color(255, 255, 255));

        Jan30.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        Jan30.setText("  30 Jan");
        Jan30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Jan30MousePressed(evt);
            }
        });

        javax.swing.GroupLayout TTJPLayout = new javax.swing.GroupLayout(TTJP);
        TTJP.setLayout(TTJPLayout);
        TTJPLayout.setHorizontalGroup(
            TTJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(TTJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Jan30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        TTJPLayout.setVerticalGroup(
            TTJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(TTJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Jan30, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        PinkBackground.add(TTJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        HomepageText4.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        HomepageText4.setForeground(new java.awt.Color(178, 169, 169));
        HomepageText4.setText("_________________________");
        PinkBackground.add(HomepageText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        PhoneInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        PhoneInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TimeIcon.setFont(new java.awt.Font("Book Antiqua", 1, 13)); // NOI18N
        TimeIcon.setText("12:00");

        BatteryIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        WiFiIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        NetworkIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        javax.swing.GroupLayout PhoneInfoPanelLayout = new javax.swing.GroupLayout(PhoneInfoPanel);
        PhoneInfoPanel.setLayout(PhoneInfoPanelLayout);
        PhoneInfoPanelLayout.setHorizontalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhoneInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeIcon)
                .addGap(202, 202, 202)
                .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        PhoneInfoPanelLayout.setVerticalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhoneInfoPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PinkBackground.add(PhoneInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PinkBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PinkBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jan20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jan20MousePressed
        // TODO add your handling code here:
        date = "20";
        dispose();
        Time T = new Time();
        T.setVisible(true);
    }//GEN-LAST:event_Jan20MousePressed

    private void BackLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMousePressed
        // TODO add your handling code here:
        dispose();
        Centers C = new Centers();
        C.setVisible(true);
    }//GEN-LAST:event_BackLabelMousePressed

    private void Jan19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jan19MousePressed
        // TODO add your handling code here:
        date = "19";
        dispose();
        Time T = new Time();
        T.setVisible(true);
    }//GEN-LAST:event_Jan19MousePressed

    private void Jan25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jan25MousePressed
        // TODO add your handling code here:
        date = "25";
        dispose();
        Time T = new Time();
        T.setVisible(true);
    }//GEN-LAST:event_Jan25MousePressed

    private void Jan30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jan30MousePressed
        // TODO add your handling code here:
        date = "30";
        dispose();
        Time T = new Time();
        T.setVisible(true);
    }//GEN-LAST:event_Jan30MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Date().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLabel;
    private javax.swing.JLabel BatteryIcon;
    private javax.swing.JLabel CertainCenter;
    private javax.swing.JLabel HomepageText2;
    private javax.swing.JLabel HomepageText4;
    private javax.swing.JLabel Jan19;
    private javax.swing.JLabel Jan20;
    private javax.swing.JLabel Jan25;
    private javax.swing.JLabel Jan30;
    private javax.swing.JLabel MenuIcon;
    private javax.swing.JPanel NJP;
    private javax.swing.JLabel NetworkIcon;
    private javax.swing.JLabel NextLabel;
    private javax.swing.JPanel PhoneInfoPanel;
    private javax.swing.JPanel PinkBackground;
    private javax.swing.JPanel TFJP;
    private javax.swing.JPanel TJP;
    private javax.swing.JPanel TTJP;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel TimeIcon;
    private javax.swing.JPanel UbMenu;
    private javax.swing.JLabel WiFiIcon;
    private javax.swing.JLabel calIcon;
    // End of variables declaration//GEN-END:variables
}
