/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    boolean validInfo;
    public static User u;
    
    public LogIn() {
        initComponents();
    //---------------------------------Icons----------------------------------//
    
        ImageIcon Menu = new ImageIcon("Icon\\menu.png");
        ImageIcon MenuS = new ImageIcon(Menu.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        MenuIcon.setIcon(MenuS);
        
        ImageIcon User = new ImageIcon("Icon\\user.png");
        ImageIcon UserS = new ImageIcon(User.getImage().getScaledInstance(120, 125, Image.SCALE_SMOOTH));
        UserIcon.setIcon(UserS);
        
        ImageIcon Battery = new ImageIcon("Icon\\battery-status.png");
        ImageIcon BatteryS = new ImageIcon(Battery.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        BatteryIcon.setIcon(BatteryS);
        
        ImageIcon WiFi = new ImageIcon("Icon\\wifi.png");
        ImageIcon WiFiS = new ImageIcon(WiFi.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        WiFiIcon.setIcon(WiFiS);
        
        ImageIcon Network = new ImageIcon("Icon\\signal.png");
        ImageIcon NetworkS = new ImageIcon(Network.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        NetworkIcon.setIcon(NetworkS);
        
        //Initalise Text
        ID_Error.setText(" ");
        Password_Error.setText(" ");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PinkBackground = new javax.swing.JPanel();
        UserIcon = new javax.swing.JLabel();
        PWText = new javax.swing.JLabel();
        LogInText = new javax.swing.JLabel();
        IDText = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        Enter = new javax.swing.JButton();
        SignUp = new javax.swing.JLabel();
        UbMenu = new javax.swing.JPanel();
        Text = new javax.swing.JLabel();
        MenuIcon = new javax.swing.JLabel();
        PhoneInfoPanel = new javax.swing.JPanel();
        TimeIcon = new javax.swing.JLabel();
        BatteryIcon = new javax.swing.JLabel();
        WiFiIcon = new javax.swing.JLabel();
        NetworkIcon = new javax.swing.JLabel();
        ID_Error = new javax.swing.JLabel();
        Password_Error = new javax.swing.JLabel();
        UserExisted = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PinkBackground.setBackground(new java.awt.Color(255, 230, 230));
        PinkBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PinkBackground.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, 125));

        PWText.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        PWText.setText("Password:");
        PinkBackground.add(PWText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        LogInText.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        LogInText.setText("Log in");
        PinkBackground.add(LogInText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        IDText.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        IDText.setText("ID/Iqama:");
        PinkBackground.add(IDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        PinkBackground.add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 130, -1));

        Enter.setBackground(new java.awt.Color(255, 255, 255));
        Enter.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        Enter.setText("Enter");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });
        PinkBackground.add(Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 100, 40));

        SignUp.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        SignUp.setText("New user? sign up");
        SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SignUpMousePressed(evt);
            }
        });
        PinkBackground.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        UbMenu.setBackground(new java.awt.Color(255, 204, 204));
        UbMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        Text.setText("Blood Donation");
        Text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        UbMenu.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 28));
        UbMenu.add(MenuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 30, 30));

        PinkBackground.add(UbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 50));

        PhoneInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        PhoneInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TimeIcon.setFont(new java.awt.Font("Book Antiqua", 1, 13)); // NOI18N
        TimeIcon.setText("12:00");

        BatteryIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        WiFiIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        NetworkIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        javax.swing.GroupLayout PhoneInfoPanelLayout = new javax.swing.GroupLayout(PhoneInfoPanel);
        PhoneInfoPanel.setLayout(PhoneInfoPanelLayout);
        PhoneInfoPanelLayout.setHorizontalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhoneInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeIcon)
                .addGap(202, 202, 202)
                .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        PhoneInfoPanelLayout.setVerticalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhoneInfoPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PinkBackground.add(PhoneInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 20));

        ID_Error.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        ID_Error.setForeground(new java.awt.Color(255, 51, 51));
        PinkBackground.add(ID_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 120, 20));

        Password_Error.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        Password_Error.setForeground(new java.awt.Color(255, 51, 51));
        PinkBackground.add(Password_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, 20));

        UserExisted.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        UserExisted.setForeground(new java.awt.Color(255, 51, 51));
        PinkBackground.add(UserExisted, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 60, 20));
        PinkBackground.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 130, -1));

        getContentPane().add(PinkBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed

    //--------------------------------Checks----------------------------------//
        boolean validPassword = checkPassword();
        boolean validID = checkID();
        boolean vaildExist = isExist();
        
    //-------------------------------Combine----------------------------------//
        validInfo = validPassword && validID && vaildExist;
        
    //--------------------------------Reslut----------------------------------//
        //if Result is true, go Homepage
        if (validInfo == true) {
            Homepage H = new Homepage();
            H.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_EnterActionPerformed

    private void SignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMousePressed
        
        //If Sign Up Pressed go to SingUp Interface
        SignUp s = new SignUp();
        s.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_SignUpMousePressed

    private boolean isExist(){

    //------------------------Initalise------------------------//
        //Get user info. from labels
        String id = IDField.getText();
        String password = new String(Pass.getPassword());

        //make user object
        User userTemp = new User(id, password);

        //-------------------------Search--------------------------//
        //Search for the user
        userTemp = User.search(userTemp);

        //----------------------Search Result----------------------//
        //if the user info not found
        if (userTemp == null) {
            UserExisted.setText("Not Found");
            return false;
        }

        //--------------------------Return-------------------------//
        u = new User(userTemp.getID(), userTemp.getPassword());
        return true;
    }
    
    private boolean checkID() {

    //------------------------Initalise------------------------//
        boolean valid = true;
        String ID = IDField.getText();

    //--------------------------Case1--------------------------//
    
        //if ID is Equal to nothing
        if (ID.trim().equals("")) {
            ID_Error.setText("Enter Your ID/Iqama");
            ID_Error.setForeground(Color.red);
            valid = false;
        } 
        
    //--------------------------Case2--------------------------//
        
        //ID must be Only 10 digit
        else if (ID.matches("[0-9]+") && ID.length() == 10) {
            ID_Error.setText(" ");
        } 
        
    //--------------------------Case3--------------------------//
        
        //if ID not digit or not in right length
        else {
            ID_Error.setText("10-digit ID/Iqama");
            ID_Error.setForeground(Color.red);
            valid = false;
        }
        
    //-------------------------Return--------------------------//
        return valid;
    }
    
    private boolean checkPassword() {

    //------------------------Initalise------------------------//
        boolean valid = true;
        String password = new String (Pass.getPassword());
        Password_Error.setText("");

    //--------------------------Case1--------------------------//
        
        //Equal to nothing
        if (password.trim().equals("")) {
            valid = false;
            Password_Error.setText("Enter Password");
            Password_Error.setForeground(Color.red);

            Pass.setText("");

        } 
    
    //--------------------------Cas2--------------------------//
        
        //Correct format
        else if (password.matches("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\\s).{6,10}$")) {
            
        } 
        
    //--------------------------Case3--------------------------//
        
        //not in the right format
        else {
            valid = false;
            Password_Error.setText("Incorrect Password");
            Password_Error.setForeground(Color.red);
            
            Pass.setText("");
        }

    //-------------------------Return--------------------------//
        return valid;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BatteryIcon;
    private javax.swing.JButton Enter;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDText;
    private javax.swing.JLabel ID_Error;
    private javax.swing.JLabel LogInText;
    private javax.swing.JLabel MenuIcon;
    private javax.swing.JLabel NetworkIcon;
    private javax.swing.JLabel PWText;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JLabel Password_Error;
    private javax.swing.JPanel PhoneInfoPanel;
    private javax.swing.JPanel PinkBackground;
    private javax.swing.JLabel SignUp;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel TimeIcon;
    private javax.swing.JPanel UbMenu;
    private javax.swing.JLabel UserExisted;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel WiFiIcon;
    // End of variables declaration//GEN-END:variables
}
