/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Interfaces.Centers.center;
import static Interfaces.Date_Time.date;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class Time extends javax.swing.JFrame {

    /**
     * Creates new form Time
     */
    
    public static String time_delete;
    
    public Time() {
        initComponents();
        
        ImageIcon Menu = new ImageIcon("Icon\\menu.png");
        ImageIcon MenuS = new ImageIcon(Menu.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        MenuIcon.setIcon(MenuS);        
       
        ImageIcon Battery = new ImageIcon("Icon\\battery-status.png");
        ImageIcon BatteryS = new ImageIcon(Battery.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        BatteryIcon.setIcon(BatteryS);
        
        ImageIcon WiFi = new ImageIcon("Icon\\wifi.png");
        ImageIcon WiFiS = new ImageIcon(WiFi.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        WiFiIcon.setIcon(WiFiS);
        
        ImageIcon Network = new ImageIcon("Icon\\signal.png");
        ImageIcon NetworkS = new ImageIcon(Network.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        NetworkIcon.setIcon(NetworkS);
        
        Day.setText(date);
        CenterText.setText(center + " Center");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PinkBackground = new javax.swing.JPanel();
        UbMenu = new javax.swing.JPanel();
        Text = new javax.swing.JLabel();
        MenuIcon = new javax.swing.JLabel();
        NextLabel = new javax.swing.JLabel();
        CenterText = new javax.swing.JLabel();
        LineText1 = new javax.swing.JLabel();
        LineText2 = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        NJP = new javax.swing.JPanel();
        T8 = new javax.swing.JLabel();
        TJP = new javax.swing.JPanel();
        T10 = new javax.swing.JLabel();
        TFJP = new javax.swing.JPanel();
        T12_30 = new javax.swing.JLabel();
        TTJP = new javax.swing.JPanel();
        T9_15 = new javax.swing.JLabel();
        Day = new javax.swing.JLabel();
        PhoneInfoPanel = new javax.swing.JPanel();
        TimeIcon = new javax.swing.JLabel();
        BatteryIcon = new javax.swing.JLabel();
        WiFiIcon = new javax.swing.JLabel();
        NetworkIcon = new javax.swing.JLabel();
        TimeText = new javax.swing.JLabel();
        Month_Year1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PinkBackground.setBackground(new java.awt.Color(255, 230, 230));
        PinkBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UbMenu.setBackground(new java.awt.Color(255, 204, 204));
        UbMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        Text.setText("Blood Donation");
        Text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        UbMenu.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 28));
        UbMenu.add(MenuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 30, 30));

        PinkBackground.add(UbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 50));

        NextLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        NextLabel.setText("Next >");
        PinkBackground.add(NextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        CenterText.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        CenterText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PinkBackground.add(CenterText, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 120, 240, 50));

        LineText1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        LineText1.setForeground(new java.awt.Color(178, 169, 169));
        LineText1.setText("_________________________");
        PinkBackground.add(LineText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        LineText2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        LineText2.setForeground(new java.awt.Color(178, 169, 169));
        LineText2.setText("_________________________");
        PinkBackground.add(LineText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        backLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        backLabel.setText("< Back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backLabelMousePressed(evt);
            }
        });
        PinkBackground.add(backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        NJP.setBackground(new java.awt.Color(255, 255, 255));

        T8.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        T8.setText("  8:00 AM");
        T8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                T8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout NJPLayout = new javax.swing.GroupLayout(NJP);
        NJP.setLayout(NJPLayout);
        NJPLayout.setHorizontalGroup(
            NJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(T8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        NJPLayout.setVerticalGroup(
            NJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(T8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PinkBackground.add(NJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 50));

        TJP.setBackground(new java.awt.Color(255, 255, 255));

        T10.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        T10.setText(" 10:00 AM");
        T10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                T10MousePressed(evt);
            }
        });

        javax.swing.GroupLayout TJPLayout = new javax.swing.GroupLayout(TJP);
        TJP.setLayout(TJPLayout);
        TJPLayout.setHorizontalGroup(
            TJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(T10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TJPLayout.setVerticalGroup(
            TJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(T10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PinkBackground.add(TJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 100, -1));

        TFJP.setBackground(new java.awt.Color(255, 255, 255));

        T12_30.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        T12_30.setText("  12:30 PM");
        T12_30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                T12_30MousePressed(evt);
            }
        });

        javax.swing.GroupLayout TFJPLayout = new javax.swing.GroupLayout(TFJP);
        TFJP.setLayout(TFJPLayout);
        TFJPLayout.setHorizontalGroup(
            TFJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(TFJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(T12_30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        TFJPLayout.setVerticalGroup(
            TFJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(TFJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(T12_30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        PinkBackground.add(TFJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 100, -1));

        TTJP.setBackground(new java.awt.Color(255, 255, 255));

        T9_15.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        T9_15.setText("   9:15 PM");
        T9_15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                T9_15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout TTJPLayout = new javax.swing.GroupLayout(TTJP);
        TTJP.setLayout(TTJPLayout);
        TTJPLayout.setHorizontalGroup(
            TTJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(TTJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(T9_15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        TTJPLayout.setVerticalGroup(
            TTJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(TTJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(T9_15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        PinkBackground.add(TTJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, -1));

        Day.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        PinkBackground.add(Day, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 192, 20, 20));

        PhoneInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        PhoneInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TimeIcon.setFont(new java.awt.Font("Book Antiqua", 1, 13)); // NOI18N
        TimeIcon.setText("12:00");

        BatteryIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        WiFiIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        NetworkIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        javax.swing.GroupLayout PhoneInfoPanelLayout = new javax.swing.GroupLayout(PhoneInfoPanel);
        PhoneInfoPanel.setLayout(PhoneInfoPanelLayout);
        PhoneInfoPanelLayout.setHorizontalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhoneInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeIcon)
                .addGap(202, 202, 202)
                .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        PhoneInfoPanelLayout.setVerticalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhoneInfoPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PinkBackground.add(PhoneInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 20));

        TimeText.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        TimeText.setText("  19 Jan");
        PinkBackground.add(TimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Month_Year1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        Month_Year1.setText(" Jan 2022");
        PinkBackground.add(Month_Year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PinkBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PinkBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T8MousePressed
        // TODO add your handling code here:
        time_delete = "8:00";
        dispose();
        Booking B = new Booking();
        B.setVisible(true);
    }//GEN-LAST:event_T8MousePressed

    private void backLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMousePressed
        // TODO add your handling code here:
        dispose();
        Date_Time D = new Date_Time();
        D.setVisible(true);
    }//GEN-LAST:event_backLabelMousePressed

    private void T10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T10MousePressed
        // TODO add your handling code here:
        time_delete = "10:00";
        dispose();
        Booking B = new Booking();
        B.setVisible(true);
    }//GEN-LAST:event_T10MousePressed

    private void T12_30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T12_30MousePressed
        // TODO add your handling code here:
        time_delete = "12:30";
        dispose();
        Booking B = new Booking();
        B.setVisible(true);
    }//GEN-LAST:event_T12_30MousePressed

    private void T9_15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T9_15MousePressed
        // TODO add your handling code here:
        time_delete = "9:15";
        dispose();
        Booking B = new Booking();
        B.setVisible(true);
    }//GEN-LAST:event_T9_15MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BatteryIcon;
    private javax.swing.JLabel CenterText;
    private javax.swing.JLabel Day;
    private javax.swing.JLabel LineText1;
    private javax.swing.JLabel LineText2;
    private javax.swing.JLabel MenuIcon;
    private javax.swing.JLabel Month_Year1;
    private javax.swing.JPanel NJP;
    private javax.swing.JLabel NetworkIcon;
    private javax.swing.JLabel NextLabel;
    private javax.swing.JPanel PhoneInfoPanel;
    private javax.swing.JPanel PinkBackground;
    private javax.swing.JLabel T10;
    private javax.swing.JLabel T12_30;
    private javax.swing.JLabel T8;
    private javax.swing.JLabel T9_15;
    private javax.swing.JPanel TFJP;
    private javax.swing.JPanel TJP;
    private javax.swing.JPanel TTJP;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel TimeIcon;
    private javax.swing.JLabel TimeText;
    private javax.swing.JPanel UbMenu;
    private javax.swing.JLabel WiFiIcon;
    private javax.swing.JLabel backLabel;
    // End of variables declaration//GEN-END:variables
}
