/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Requirements extends javax.swing.JFrame {

    /**
     * Creates new form Requirements
     */
    public Requirements() {
        
        initComponents();
        
        ImageIcon Menu = new ImageIcon("Icon\\menu.png");
        ImageIcon MenuS = new ImageIcon(Menu.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        MenuIcon.setIcon(MenuS);
        
        ImageIcon Req = new ImageIcon("Icon\\shopping-list.png");
        ImageIcon ReqS = new ImageIcon(Req.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH));
      //  ReqIcon.setIcon(ReqS);
        
        ImageIcon Battery = new ImageIcon("Icon\\battery-status.png");
        ImageIcon BatteryS = new ImageIcon(Battery.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        BatteryIcon.setIcon(BatteryS);
        
        ImageIcon WiFi = new ImageIcon("Icon\\wifi.png");
        ImageIcon WiFiS = new ImageIcon(WiFi.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        WiFiIcon.setIcon(WiFiS);
        
        ImageIcon Network = new ImageIcon("Icon\\signal.png");
        ImageIcon NetworkS = new ImageIcon(Network.getImage().getScaledInstance(13, 13, Image.SCALE_SMOOTH));
        NetworkIcon.setIcon(NetworkS);
        
        ButtonGroup b = new ButtonGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        PinkBackground = new javax.swing.JPanel();
        HomepageText = new javax.swing.JLabel();
        ReqTextBG = new javax.swing.JPanel();
        ReqText = new javax.swing.JLabel();
        ReqText1 = new javax.swing.JLabel();
        ReqText2 = new javax.swing.JLabel();
        ReqText3 = new javax.swing.JLabel();
        ReqText4 = new javax.swing.JLabel();
        ReqText5 = new javax.swing.JLabel();
        ReqText7 = new javax.swing.JLabel();
        ReqText8 = new javax.swing.JLabel();
        ReqText9 = new javax.swing.JLabel();
        Month = new javax.swing.JSpinner();
        yes = new javax.swing.JRadioButton();
        No = new javax.swing.JRadioButton();
        ReqText10 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        Weight = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        age_Error = new javax.swing.JLabel();
        w_Error = new javax.swing.JLabel();
        UbMenu = new javax.swing.JPanel();
        Text = new javax.swing.JLabel();
        MenuIcon = new javax.swing.JLabel();
        PhoneInfoPanel = new javax.swing.JPanel();
        TimeIcon = new javax.swing.JLabel();
        BatteryIcon = new javax.swing.JLabel();
        WiFiIcon = new javax.swing.JLabel();
        NetworkIcon = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PinkBackground.setBackground(new java.awt.Color(255, 230, 230));
        PinkBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomepageText.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        HomepageText.setText("Requirements Test");
        PinkBackground.add(HomepageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        ReqTextBG.setBackground(new java.awt.Color(255, 204, 204));
        ReqTextBG.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 132, 132), java.awt.Color.white));

        ReqText.setBackground(new java.awt.Color(255, 204, 204));
        ReqText.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText.setForeground(new java.awt.Color(61, 9, 9));
        ReqText.setText("Months");

        ReqText1.setBackground(new java.awt.Color(255, 204, 204));
        ReqText1.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText1.setForeground(new java.awt.Color(61, 9, 9));

        ReqText2.setBackground(new java.awt.Color(255, 204, 204));
        ReqText2.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText2.setForeground(new java.awt.Color(61, 9, 9));

        ReqText3.setBackground(new java.awt.Color(255, 204, 204));
        ReqText3.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText3.setForeground(new java.awt.Color(61, 9, 9));

        ReqText4.setBackground(new java.awt.Color(255, 204, 204));
        ReqText4.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText4.setForeground(new java.awt.Color(61, 9, 9));
        ReqText4.setText("• How much do you weigh in Kgs ? ");

        ReqText5.setBackground(new java.awt.Color(255, 204, 204));
        ReqText5.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText5.setForeground(new java.awt.Color(61, 9, 9));
        ReqText5.setText("• Are you Currently Taking any Atibiotics ");

        ReqText7.setBackground(new java.awt.Color(255, 204, 204));
        ReqText7.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText7.setForeground(new java.awt.Color(61, 9, 9));

        ReqText8.setBackground(new java.awt.Color(255, 204, 204));
        ReqText8.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText8.setForeground(new java.awt.Color(61, 9, 9));

        ReqText9.setBackground(new java.awt.Color(255, 204, 204));
        ReqText9.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText9.setForeground(new java.awt.Color(61, 9, 9));
        ReqText9.setText("• How Many Months ago did you donated? ");

        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });

        ReqText10.setBackground(new java.awt.Color(255, 204, 204));
        ReqText10.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 14)); // NOI18N
        ReqText10.setForeground(new java.awt.Color(61, 9, 9));
        ReqText10.setText("•How Old Are You?");

        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });

        Weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightActionPerformed(evt);
            }
        });

        jButton1.setText("OK");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReqTextBGLayout = new javax.swing.GroupLayout(ReqTextBG);
        ReqTextBG.setLayout(ReqTextBGLayout);
        ReqTextBGLayout.setHorizontalGroup(
            ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReqTextBGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(9, 9, 9))
            .addGroup(ReqTextBGLayout.createSequentialGroup()
                .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addComponent(ReqText4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(ReqText1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReqText8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReqText7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addComponent(ReqText9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReqText2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReqText3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ReqText10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(age_Error))
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(w_Error))
                    .addComponent(ReqText5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ReqTextBGLayout.createSequentialGroup()
                .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReqText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(yes)
                        .addGap(30, 30, 30)
                        .addComponent(No))
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReqTextBGLayout.setVerticalGroup(
            ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReqTextBGLayout.createSequentialGroup()
                .addComponent(ReqText10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age_Error))
                .addGap(10, 10, 10)
                .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReqText1)
                    .addComponent(ReqText4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(w_Error))
                .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(ReqText2)
                        .addGap(0, 0, 0)
                        .addComponent(ReqText3))
                    .addGroup(ReqTextBGLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ReqText9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReqText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(ReqText5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReqTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No)
                    .addComponent(yes))
                .addGap(43, 43, 43)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(ReqText8)
                .addGap(0, 0, 0)
                .addComponent(ReqText7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        PinkBackground.add(ReqTextBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 390));

        UbMenu.setBackground(new java.awt.Color(255, 204, 204));
        UbMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        Text.setText("Blood Donation");
        Text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        UbMenu.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 28));
        UbMenu.add(MenuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 30, 30));

        PinkBackground.add(UbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 50));

        PhoneInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        PhoneInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TimeIcon.setFont(new java.awt.Font("Book Antiqua", 1, 13)); // NOI18N
        TimeIcon.setText("12:00");

        BatteryIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        WiFiIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        NetworkIcon.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N

        javax.swing.GroupLayout PhoneInfoPanelLayout = new javax.swing.GroupLayout(PhoneInfoPanel);
        PhoneInfoPanel.setLayout(PhoneInfoPanelLayout);
        PhoneInfoPanelLayout.setHorizontalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhoneInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeIcon)
                .addGap(202, 202, 202)
                .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        PhoneInfoPanelLayout.setVerticalGroup(
            PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhoneInfoPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(PhoneInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NetworkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WiFiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatteryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PinkBackground.add(PhoneInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 20));

        backLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        backLabel.setText("< Back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backLabelMousePressed(evt);
            }
        });
        PinkBackground.add(backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PinkBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PinkBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMousePressed
        // TODO add your handling code here:
        dispose();
        Homepage H = new Homepage();
        H.setVisible(true);
    }//GEN-LAST:event_backLabelMousePressed

    private void WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AgeActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean validage = checkAge();
        boolean validweight = checkWeight();
        boolean vaildmonth = checkMonth();
        boolean validans= checkantibiotics();

        //-------------------------------Combine----------------------------------//
        boolean Validinfo = validweight && vaildmonth && validans&&validage;

        //--------------------------------Result----------------------------------//
        //if Result is true, go Center
        if (Validinfo == true) {
            Homepage H = new Homepage();
            H.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Requirements().setVisible(true);
            }
        });
    }
       private boolean checkAge() {

    //------------------------Initalise------------------------//
        boolean valid = true;
        String age = Age.getText();

    //--------------------------Case1--------------------------//
   
        //if Age is Equal to nothing
        if (age.trim().equals("")) {
            age_Error.setText("Enter Your Age");
            age_Error.setForeground(Color.red);
            valid = false;
        } 
        
    //--------------------------Case2--------------------------//
        
        //Age must be digit 
      /*  else if (age.matches("[0-9]+" )&& age.length()==2) {
             age_Error.setText("Enter Valid Age");
             age_Error.setForeground(Color.red);
            valid = false;
        } 
        */
    //--------------------------Case3--------------------------//
        
        //Age must be above 18
        else {
            int n=Integer.parseInt(age);
            if (n>=18){
                valid= true;
            }
            else{
           // Error Window NOT ELIGIBLE (JOPTIONPANE)
           JOptionPane j= new JOptionPane();
           JOptionPane.showMessageDialog(null, "Sorry , You are not Eligible for Donation");
            valid = false;
        }}
        
    //-------------------------Return--------------------------//
        return valid;
    }
         private boolean checkWeight() {

    //------------------------Initalise------------------------//
        boolean valid = true;
        String weight = Weight.getText();

    //--------------------------Case1--------------------------//
   
        //if Age is Equal to nothing
        if (weight.trim().equals("")) {
            w_Error.setText("Enter Your Weight");
            w_Error.setForeground(Color.red);
            valid = false;
        } 
        
    //--------------------------Case2--------------------------//
        
        //Age must be digit 
      /*  else if (weight.matches("[0-9]+")&&weight.length()==2) {
             w_Error.setText("Enter Valid Weight");
             w_Error.setForeground(Color.red);
            valid = false;
        } */
        
    //--------------------------Case3--------------------------//
        
        //Weight must be above 50
        else  {
            int n=Integer.parseInt(weight);
            if (n>=50){
                valid= true;
            }
            else{
           // Error Window NOT ELIGIBLE (JOPTIONPANE)
           JOptionPane j= new JOptionPane();
           j.showMessageDialog(null, "Sorry , You are not Eligible for Donation");
            valid = false;
        }}
        
    //-------------------------Return--------------------------//
        return valid;
    }
           private boolean checkMonth() {
        boolean valid = true;
        String month = Month.getValue().toString();
        // must be more than 3 months 
        
        int m =Integer.parseInt(month);
        
        if (m<3) {
            // Error Window NOT ELIGIBLE (JOPTIONPANE)
           JOptionPane j= new JOptionPane();
           j.showMessageDialog(null, "Sorry , You are not Eligible for Donation");
            valid = false;
        } 
        return valid;
    }
             private boolean checkantibiotics() {
                    boolean valid = true;
                    String y = yes.ge;
                    String n = No.getText();
              if(y.equals(null))  {
                    JOptionPane j= new JOptionPane();
           j.showMessageDialog(null, "Congratulation! You can Donate");
              }    
              else{
                JOptionPane j= new JOptionPane();
           j.showMessageDialog(null, "Sorry , You are not Eligible for Donation");
            valid = false;  
              }
              return valid;
             }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JLabel BatteryIcon;
    private javax.swing.JLabel HomepageText;
    private javax.swing.JLabel MenuIcon;
    private javax.swing.JSpinner Month;
    private javax.swing.JLabel NetworkIcon;
    private javax.swing.JRadioButton No;
    private javax.swing.JPanel PhoneInfoPanel;
    private javax.swing.JPanel PinkBackground;
    private javax.swing.JLabel ReqText;
    private javax.swing.JLabel ReqText1;
    private javax.swing.JLabel ReqText10;
    private javax.swing.JLabel ReqText2;
    private javax.swing.JLabel ReqText3;
    private javax.swing.JLabel ReqText4;
    private javax.swing.JLabel ReqText5;
    private javax.swing.JLabel ReqText7;
    private javax.swing.JLabel ReqText8;
    private javax.swing.JLabel ReqText9;
    private javax.swing.JPanel ReqTextBG;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel TimeIcon;
    private javax.swing.JPanel UbMenu;
    private javax.swing.JTextField Weight;
    private javax.swing.JLabel WiFiIcon;
    private javax.swing.JLabel age_Error;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel w_Error;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
